import { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type LangCode = 'ar' | 'en';

interface LangInfo {
  code: LangCode;
  name: string;
  nativeName: string;
  flag: string;
  dir: 'rtl' | 'ltr';
}

const LANGUAGES: LangInfo[] = [
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', dir: 'ltr' },
];

type TranslationKeys = Record<string, string>;
type Translations = Record<LangCode, TranslationKeys>;

const translations: Translations = {
  // ═══════════════════════════════════════════════════════════════
  // ARABIC (العربية السعودية الرسمية)
  // ═══════════════════════════════════════════════════════════════
  ar: {
    'actions': 'الإجراءات',
    'activeBookings': 'حجوزات نشطة',
    'activeTraders': 'تاجر نشط',
    'activityType': 'نوع النشاط',
    'add': 'إضافة',
    'address': 'العنوان',
    'ai.online_ready': 'متصل ومستعد للمساعدة',
    'ai.placeholder': 'اكتب سؤالك هنا...',
    'ai.title': 'المساعد الذكي',
    'aiAssistantDesc': 'مساعد ذكاء اصطناعي يساعدك في اختيار الجناح المثالي وإدارة عملياتك',
    'aiAssistantFeature': 'مساعد ذكي',
    'aiRecommendations': 'توصيات ذكية',
    'allRightsReserved': 'جميع الحقوق محفوظة',
    'amount': 'المبلغ',
    'analytics.conversion_rate': 'معدل التحويل',
    'analytics.last_6_months': 'آخر 6 أشهر',
    'analytics.revenue': 'الإيرادات',
    'analytics.revenue_visitors': 'الإيرادات والزوار',
    'analytics.title': 'التحليلات',
    'analytics.top_expos': 'أفضل المعارض أداءً',
    'analytics.visitors': 'الزوار',
    'analyticsDesc': 'تقارير وتحليلات شاملة لأداء معارضك واستثماراتك',
    'analyticsFeature': 'تحليلات متقدمة',
    'annualExpos': 'معرض سنوي',
    'approvals': 'الموافقات والطلبات',
    'attachments': 'المرفقات والوثائق',
    'auth.account_created': 'تاريخ إنشاء الحساب:',
    'auth.account_created_welcome_to': 'تم إنشاء حسابك بنجاح! مرحباً بك في مهام إكسبو',
    'auth.bank_letter_confirming_account': 'خطاب من البنك يؤكد بيانات الحساب',
    'auth.successfully_registered': 'تم التسجيل بنجاح!',
    'auth.valid_commercial_register_copy': 'صورة من السجل التجاري ساري المفعول',
    'automotive': 'سيارات',
    'back': 'رجوع',
    'bookNewBooth': 'حجز جناح جديد',
    'booking.area': 'المساحة',
    'booking.booth': 'الجناح',
    'booking.price': 'السعر',
    'booking.title': 'الحجوزات',
    'booking.zone': 'المنطقة',
    'booking_flow.complete_before_timeout': 'أكمل الحجز قبل انتهاء الوقت',
    'booking_flow.select_activity': 'اختر نوع النشاط',
    'bookings.3_competitors_booked_in': '3 منافسين حجزوا في نفس المعرض',
    'bookings.book_30_days_early': 'احجز قبل 30 يوم واحصل على خصم 15%',
    'bookings.booking_request_submitted': 'تم إرسال طلب الحجز بنجاح!',
    'bookings.bookings': 'حجز',
    'bookings.completed_bookings': 'حجوزات مكتملة',
    'bookings.excellent_i_would_like': 'ممتاز، أريد حجزه من فضلكم',
    'bookings.expo': 'المعرض',
    'bookings.my_bookings': 'حجوزاتي',
    'bookings.new_booking': 'حجز جديد',
    'bookings.no_bookings_found': 'لا توجد حجوزات',
    'bookings.search_placeholder': 'ابحث برقم الطلب أو المعرض...',
    'booth_type.corner': 'زاوية',
    'booth_type.island': 'جزيرة',
    'booth_type.premium': 'مميز',
    'booth_type.standard': 'عادي',
    'booths': 'جناح متاح',
    'boothsBooked': 'أجنحة محجوزة هذا الشهر',
    'brand.name': 'مهام إكسبو',
    'brand.tagline': 'منصة المعارض الذكية',
    'browseExpos': 'تصفح المعارض',
    'cancel': 'إلغاء',
    'city': 'المدينة',
    'close': 'إغلاق',
    'comingSoon': 'قريباً',
    'common.': 'English',
    'common.active_events': 'فعالية نشطة',
    'common.advanced_filters': 'فلاتر متقدمة',
    'common.all': 'الكل',
    'common.amenities': 'المرافق',
    'common.approved': 'تمت الموافقة',
    'common.ar': 'en',
    'common.available': 'متاح:',
    'common.available_corner': 'متاح (زاوية)',
    'common.available_island': 'متاح (جزيرة)',
    'common.available_premium': 'متاح (مميز)',
    'common.available_standard': 'متاح (عادي)',
    'common.bank': 'تحويل بنكي',
    'common.bank_certificate': 'شهادة بنكية',
    'common.beneficiary': 'المستفيد',
    'common.by_availability': 'حسب التوفر',
    'common.by_date': 'حسب التاريخ',
    'common.call_us': 'اتصل بنا',
    'common.cancel': 'إلغاء',
    'common.card': 'بطاقة',
    'common.card_number': 'رقم البطاقة',
    'common.category': 'التصنيف',
    'common.cats': 'تصنيف',
    'common.city': 'المدينة',
    'common.coming_soon': 'قريباً',
    'common.competitor_analysis': 'تحليل المنافسين',
    'common.confirm': 'تأكيد الحجز',
    'common.contact_us': 'تواصل معنا',
    'common.criteria': 'المعيار',
    'common.date': 'التاريخ',
    'common.days': 'أيام',
    'common.download_receipt': 'تحميل الإيصال',
    'common.due': 'تاريخ الاستحقاق',
    'common.entrance': 'المدخل',
    'common.enus': 'ar-SA',
    'common.expected_visitors': 'زائر متوقع',
    'common.expiry': 'تاريخ الانتهاء',
    'common.filters': 'فلاتر',
    'common.helpful': 'مفيد',
    'common.hold_30min': 'حجز مؤقت 30 د',
    'common.important_notes': 'ملاحظات مهمة:',
    'common.included_amenities': 'المرافق المتضمنة',
    'common.loading': 'جاري التحميل...',
    'common.location': 'الموقع',
    'common.no_data': 'لا توجد بيانات',
    'common.official': 'رسمي',
    'common.online': '• متصل',
    'common.optional': 'اختياري',
    'common.order': 'رقم الطلب',
    'common.pending': 'قيد الانتظار',
    'common.permissions': 'الصلاحيات',
    'common.popular': 'شائع',
    'common.pricem': 'سعر/م²',
    'common.print': 'طباعة',
    'common.printing': 'جاري الطباعة...',
    'common.processing': 'جاري المعالجة...',
    'common.quick_links': 'روابط سريعة',
    'common.read_only': 'غير قابل للتعديل',
    'common.recent_activity': 'النشاط الأخير',
    'common.required': 'مطلوب',
    'common.sar': 'ر.س',
    'common.selected': 'محدد',
    'common.smart_recommendations': 'توصيات ذكية لك',
    'common.starts_from': 'يبدأ من',
    'common.status': 'الحالة',
    'common.status_tracking': 'تتبع الحالة',
    'common.submitted': 'تم الإرسال',
    'common.subtotal': 'المجموع الفرعي',
    'common.suggested_expos': 'معارض مقترحة',
    'common.total': 'الإجمالي',
    'common.track_request': 'متابعة الطلب',
    'common.trader': 'تاجر',
    'common.type': 'النوع',
    'common.unit': 'وحدة',
    'common.uploading': 'جاري الرفع...',
    'common.value': 'القيمة',
    'common.vat_15': 'ضريبة القيمة المضافة (15%)',
    'common.vat_certificate': 'شهادة ضريبة القيمة المضافة',
    'common.verified_successfully': 'تم التحقق بنجاح',
    'common.view': 'عرض',
    'common.view_all': 'عرض الكل',
    'common.view_details': 'عرض التفاصيل',
    'common.yesterday': 'أمس',
    'common.your_comment': 'تعليقك',
    'communications': 'المراسلات',
    'companyName': 'اسم الشركة',
    'completeProfile': 'أكمل ملفك الشخصي',
    'confirm': 'تأكيد',
    'contactUs': 'تواصل معنا',
    'contract.download': 'تحميل العقد',
    'contract.sign': 'توقيع العقد',
    'contract.title': 'العقود',
    'contract.view': 'عرض العقد',
    'contract_status.draft': 'مسودة',
    'contract_status.signed': 'موقّع',
    'contracts.add_team_members_to': 'أضف أعضاء فريقك لتمكينهم من إدارة الحجوزات والعقود',
    'contracts.after_booking_approval_the': 'بعد الموافقة على حجزك، سيظهر العقد في صفحة العقود. يمكنك مراجعة الشروط والتوقيع بضغطة زر.',
    'contracts.by_clicking_confirm_signature': 'بالنقر على "تأكيد التوقيع" فإنك توافق على جميع بنود العقد',
    'contracts.confirm_signature': 'تأكيد التوقيع',
    'contracts.contract_terms': 'بنود العقد',
    'contracts.contracts_will_appear_here': 'ستظهر العقود هنا بعد الموافقة على حجزك',
    'contracts.digital_signature': 'التوقيع الرقمي',
    'contracts.draft_awaiting_signature': 'مسودة - بانتظار التوقيع',
    'contracts.how_to_sign_contracts': 'كيف أوقع العقد إلكترونياً؟',
    'contracts.i_confirm_that_i': 'أقر بأنني قرأت وفهمت جميع بنود العقد وأوافق عليها',
    'contracts.my_contracts': 'عقودي',
    'contracts.no_contracts_yet': 'لا توجد عقود',
    'contracts.of_course_we_will': 'بالتأكيد! سنرسل لك عرض سعر خلال 24 ساعة. هل لديك تصور معين للتصميم؟',
    'contracts.sign': 'توقيع العقد',
    'contracts.signed': 'تم التوقيع',
    'contracts.signed_contracts': 'العقود الموقعة',
    'contracts.supervisor_note': 'ملاحظة المشرف',
    'contracts.unsigned': 'بانتظار التوقيع',
    'contracts.yes_i_want_a': 'نعم، أريد تصميم عصري بألوان الشركة (أزرق وذهبي)',
    'country': 'الدولة',
    'createAccount': 'إنشاء الحساب',
    'ctaSubtitle': 'انضم إلى مئات التجار الناجحين واحجز جناحك في أفضل المعارض',
    'ctaTitle': 'ابدأ رحلتك مع مهام إكسبو',
    'dammam': 'الدمام',
    'dashboard.manage_expos': 'إدارة المعارض',
    'dashboard.matching_expos': 'معارض تناسب نشاطك التجاري',
    'dashboard.monthly_bookings': 'الحجوزات الشهرية',
    'dashboard.my_stats': 'إحصائياتي',
    'dashboard.overall_rating': 'التقييم العام',
    'dashboard.recent_bookings': 'آخر الحجوزات',
    'dashboard.required_actions': 'إجراءات مطلوبة',
    'dashboard.total_bookings': 'إجمالي الحجوزات',
    'dashboard.total_payments': 'إجمالي المدفوعات',
    'dashboard.total_spent': 'إجمالي الإنفاق',
    'dashboard.upcoming_expos': 'معارض قادمة',
    'dashboardSubtitle': 'إليك ملخص نشاطك',
    'date': 'التاريخ',
    'delete': 'حذف',
    'details': 'التفاصيل',
    'digitalContracts': 'عقود رقمية',
    'digitalContractsDesc': 'وقّع عقودك إلكترونياً بأمان تام مع تتبع كامل لجميع المراحل',
    'download': 'تحميل',
    'edit': 'تعديل',
    'email': 'البريد الإلكتروني',
    'employeeBadges': 'باجات الموظفين',
    'enterOTP': 'أدخل رمز التحقق المرسل إلى',
    'enterPhone': 'أدخل رقم الجوال',
    'entryPermits': 'تصاريح الدخول والخروج',
    'error': 'خطأ',
    'expo.about': 'عن الفعالية',
    'expo.all_zones': 'جميع المناطق',
    'expo.ask_about_the_best': 'اسأل عن أفضل الوحدات والتوصيات المخصصة لنشاطك التجاري في فعاليات على خطاه وبوليفارد وورلد',
    'expo.available_booths': 'الأجنحة المتاحة',
    'expo.available_units': 'الوحدات المتاحة',
    'expo.back_to_expos': 'العودة للمعارض',
    'expo.book_unit': 'احجز وحدتك الآن',
    'expo.booking_info': 'معلومات الحجز',
    'expo.booth_a12': 'جناح A12',
    'expo.booth_design_service_request': 'تم تأكيد طلب خدمة تصميم البوث. سيتواصل معك المصمم قريباً.',
    'expo.booth_held_for_30': 'تم حجز الجناح مؤقتاً لمدة 30 دقيقة',
    'expo.booth_price': 'سعر الجناح',
    'expo.booth_type_distribution': 'توزيع أنواع الأجنحة',
    'expo.browse_available_expos_select': 'يمكنك حجز جناح من خلال تصفح المعارض المتاحة، اختيار المعرض، فتح الخريطة التفاعلية، واختيار الجناح المناسب. بعد إرسال الطلب، سيتم مراجعته من المشرف.',
    'expo.browse_services': 'تصفح الخدمات',
    'expo.categories': 'التصنيفات',
    'expo.contact_booking': 'تواصل للحجز',
    'expo.end_date': 'نهاية الفعالية',
    'expo.event_ended': 'انتهت هذه الفعالية',
    'expo.hello_i_want_to': 'مرحباً، أريد طلب خدمة تصميم بوث احترافي',
    'expo.hello_i_would_like': 'السلام عليكم، أود الاستفسار عن حجز الجناح A12',
    'expo.hello_yes_booth_a12': 'وعليكم السلام! نعم، الجناح A12 متاح حالياً. مساحته 12م² وسعره 13,500 ر.س',
    'expo.hide_units': 'إخفاء الوحدات',
    'expo.high_traffic_units': 'وحدات ذات حركة عالية',
    'expo.highlights': 'أبرز المميزات',
    'expo.how_to_book_a': 'كيف أحجز جناح في المعرض؟',
    'expo.join_the_waitlist_and': 'انضم لقائمة الانتظار وسنبلغك فور توفر جناح مميز',
    'expo.join_waitlist': 'انضم لقائمة الانتظار',
    'expo.marketing_reach': 'الوصول التسويقي',
    'expo.no_units': 'لا توجد وحدات متاحة',
    'expo.organizer': 'الجهة المنظمة',
    'expo.other_events': 'فعاليات أخرى',
    'expo.please_complete_identity_verification': 'يرجى إكمال التحقق من الهوية لتتمكن من حجز الأجنحة.',
    'expo.premium_booth_waitlist': 'قائمة الانتظار للأجنحة المميزة',
    'expo.price_range': 'نطاق الأسعار',
    'expo.start_browsing_expos_and': 'ابدأ بتصفح المعارض وحجز جناحك',
    'expo.start_date': 'بداية الفعالية',
    'expo.target_industries': 'الصناعات المستهدفة',
    'expo.units_near_entrance_get': 'الوحدات القريبة من المدخل تحقق 40% زيارات أكثر',
    'expo.verification_is_required_for': '• التحقق مطلوب لحجز الأجنحة وتوقيع العقود',
    'expo.view_units': 'عرض الوحدات',
    'expo.visitor_demographics': 'ديموغرافية الزوار',
    'expo.we_offer_36_services': 'نوفر أكثر من 36 خدمة تشمل: تصميم البوث، الكهرباء، اللوجستيات، التسويق، الضيافة، التصوير، والمزيد.',
    'expo.your_booking_for_booth': 'تم تأكيد حجزك للجناح A12. يرجى مراجعة صفحة الحجوزات لإكمال الإجراءات.',
    'expo.your_identity_has_been': 'تم التحقق من هويتك بنجاح. يمكنك الآن حجز الأجنحة وتوقيع العقود.',
    'export': 'تصدير',
    'expos.active': 'نشط',
    'expos.all': 'الكل',
    'expos.book_now': 'احجز الآن',
    'expos.booth': 'جناح',
    'expos.booths': 'أجنحة',
    'expos.completed': 'مكتمل',
    'expos.browse': 'تصفح المعارض',
    'expos.clear_filters': 'مسح الفلاتر',
    'expos.no_results': 'لا توجد معارض مطابقة',
    'expos.official': 'رسمي',
    'expos.upcoming': 'قادم',
    'expos.search': 'بحث في المعارض',
    'expos.search_placeholder': 'ابحث بالاسم، المدينة، أو المكان...',
    'expos.title': 'المعارض',
    'expos.visitors': 'زائر',
    'fashion': 'أزياء وموضة',
    'featuresSubtitle': 'منصة متكاملة تجمع كل ما يحتاجه التاجر في مكان واحد',
    'filter': 'تصفية',
    'food': 'أغذية ومشروبات',
    'fullName': 'الاسم الكامل',
    'furnishing': 'التأثيث والتجهيز',
    'health': 'صحة وجمال',
    'help.faq': 'الأسئلة الشائعة',
    'help.hello_how_can_we': 'مرحباً، كيف يمكننا مساعدتك؟',
    'help.how_can_we_help': 'كيف يمكننا مساعدتك اليوم؟ نحن هنا لخدمتك.',
    'help.how_to_contact_support': 'كيف أتواصل مع الدعم الفني؟',
    'help.maham_expo_support': 'دعم مهام إكسبو',
    'help.search_placeholder': 'ابحث في الأسئلة...',
    'help.ticket': 'تذكرة دعم',
    'help.no_answer_create_ticket': 'لم تجد إجابة؟ أنشئ تذكرة دعم وسنرد عليك خلال 24 ساعة',
    'help.title': 'مركز المساعدة',
    'heroSubtitle': 'اكتشف أفضل المعارض، احجز جناحك المثالي، وأدر عملياتك بالكامل من منصة واحدة مدعومة بالذكاء الاصطناعي',
    'heroTitle': 'بوابتك الذكية لعالم المعارض',
    'home.hero.cta': 'ابدأ الآن',
    'howItWorks': 'كيف يعمل',
    'instantBooking': 'حجز فوري',
    'interactiveMap': 'خريطة تفاعلية',
    'interactiveMapDesc': 'استعرض أجنحة المعرض بخريطة تفاعلية ثلاثية الأبعاد مع معلومات فورية عن كل جناح',
    'jeddah': 'جدة',
    'journeySubtitle': 'ست خطوات بسيطة لبدء مشاركتك في المعارض',
    'journeyTitle': 'رحلتك من التسجيل إلى النجاح',
    'kyc.all_documents_must_be': '• يجب أن تكون جميع المستندات سارية المفعول وواضحة',
    'kyc.commercial_register': 'السجل التجاري',
    'kyc.complete_verification': 'أكمل التحقق',
    'kyc.document_removed': 'تم حذف المستند',
    'kyc.document_uploaded_successfully': 'تم رفع المستند بنجاح',
    'kyc.documents_are_reviewed_within': '• يتم مراجعة المستندات خلال 24-48 ساعة عمل',
    'kyc.documents_rejected_please_reupload': 'تم رفض المستندات. يرجى إعادة رفع مستندات واضحة وسارية المفعول.',
    'kyc.documents_submitted_for_review': 'تم إرسال المستندات للمراجعة',
    'kyc.national_id': 'الهوية الوطنية',
    'kyc.please_upload_required_documents': 'يرجى رفع المستندات المطلوبة لإكمال التحقق',
    'kyc.status.pending': 'قيد المراجعة',
    'kyc.status.rejected': 'مرفوض',
    'kyc.status.submitted': 'مقدم',
    'kyc.status.verified': 'موثق',
    'kyc.title': 'التحقق من الهوية (KYC)',
    'kyc.upload': 'رفع المستند',
    'kyc.verification_progress': 'تقدم التحقق',
    'kyc.verification_status': 'حالة التحقق',
    'kyc.viewing_document': 'عرض المستند',
    'kyc.your_documents_are_under': 'تم إرسال مستنداتك وهي قيد المراجعة. سيتم إشعارك بالنتيجة خلال 24-48 ساعة.',
    'loading': 'جاري التحميل...',
    'login': 'تسجيل الدخول',
    'login.complete_profile_subtitle': 'أكمل بياناتك لبدء رحلتك مع مهام إكسبو',
    'login.welcome': 'مرحباً بك في مهام إكسبو! 👋',
    'loginSubtitle': 'سجّل دخولك للوصول إلى لوحة التحكم',
    'maintenance': 'طلبات الصيانة',
    'makePayment': 'إجراء دفعة',
    'makkah': 'مكة المكرمة',
    'map.add_compare': 'إضافة للمقارنة',
    'map.area': 'المساحة',
    'map.booth': 'الجناح',
    'map.booth_unavailable': 'هذا الجناح غير متاح',
    'map.compare_booths': 'مقارنة الأجنحة',
    'map.max_compare': 'الحد الأقصى 3 أجنحة للمقارنة',
    'map.price': 'السعر',
    'map.remove_compare': 'إزالة من المقارنة',
    'map.select_type': 'اختر النوع',
    'map.select_zone': 'اختر المنطقة',
    'map.title': 'الخريطة التفاعلية',
    'map.traffic': 'حركة المرور',
    'map.zone': 'المنطقة',
    'messages.live_chat': 'محادثة مباشرة',
    'messages.new_message': 'رسالة جديدة',
    'messages.search': 'بحث في الرسائل',
    'messages.select_conversation': 'اختر محادثة للبدء',
    'messages.start_conversation': 'ابدأ المحادثة',
    'messages.thanks_for_your_message': 'شكراً لرسالتك! سنرد عليك في أقرب وقت ممكن.',
    'messages.title': 'الرسائل',
    'messages.type_message': 'اكتب رسالتك...',
    'misc.accepted_formats_pdf_jpg': '• الصيغ المقبولة: PDF, JPG, PNG (حد أقصى 5MB)',
    'misc.all_transactions_are_encrypted': 'جميع المعاملات مشفرة ومحمية بمعايير PCI DSS',
    'misc.back_to_home': 'العودة للرئيسية',
    'misc.bank_transfer_details': 'تفاصيل التحويل البنكي',
    'misc.changes_saved_successfully': 'تم حفظ التغييرات بنجاح',
    'misc.click_to_select': 'انقر للتحديد',
    'misc.dammam_industrial_expo': 'معرض الدمام الصناعي',
    'misc.drag_files_here_or': 'اسحب الملفات هنا أو انقر للرفع',
    'misc.early_bird_offer': 'عرض الحجز المبكر',
    'misc.eg_nour_karam': 'مثال: نور كرم',
    'misc.food_hospitality_expo': 'معرض الغذاء والضيافة',
    'misc.hold_time_expired': 'انتهى وقت الحجز المؤقت',
    'misc.jeddah_food_expo': 'معرض جدة للأغذية',
    'misc.maham_ai_assistant': 'المساعد الذكي MAHAM AI',
    'misc.national_id_or_iqama': 'صورة من الهوية الوطنية أو الإقامة',
    'misc.new_approval_request': 'طلب موافقة جديد',
    'misc.page_not_found': 'الصفحة غير موجودة',
    'misc.please_complete_required_fields': 'يرجى إكمال الحقول المطلوبة',
    'misc.please_enter_a_title': 'يرجى إدخال العنوان',
    'misc.riyadh_tech_expo': 'معرض الرياض الدولي للتقنية',
    'misc.thanks_for_your_feedback': 'شكراً لتقييمك',
    'misc.try_changing_filters_or': 'جرب تغيير الفلاتر أو البحث',
    'misc.upload_new_attachment': 'رفع مرفق جديد',
    'misc.vat_registration_certificate': 'شهادة التسجيل في ضريبة القيمة المضافة',
    'misc.we_accept_credit_cards': 'نقبل بطاقات الائتمان، التحويل البنكي، Apple Pay، ومدى.',
    'misc.you_will_be_notified': 'سيتم إشعارك عند توفر جناح',
    'month.apr': 'أبريل',
    'month.feb': 'فبراير',
    'month.jan': 'يناير',
    'month.jun': 'يونيو',
    'month.mar': 'مارس',
    'month.may': 'مايو',
    'name': 'الاسم',
    'nav.ai': 'المساعد الذكي',
    'nav.analytics': 'التحليلات',
    'nav.bookingFlow': 'حجز جديد',
    'nav.bookings': 'الحجوزات',
    'nav.contracts': 'العقود',
    'nav.dashboard': 'لوحة التحكم',
    'nav.expos': 'المعارض',
    'nav.help': 'المساعدة',
    'nav.kyc': 'التحقق',
    'nav.logout': 'تسجيل الخروج',
    'nav.map': 'الخريطة',
    'nav.messages': 'الرسائل',
    'nav.notifications': 'الإشعارات',
    'nav.operations': 'العمليات',
    'nav.payments': 'المدفوعات',
    'nav.profile': 'الملف الشخصي',
    'nav.reviews': 'التقييمات',
    'nav.services': 'الخدمات',
    'nav.settings': 'الإعدادات',
    'nav.team': 'الفريق',
    'nav.waitlist': 'قائمة الانتظار',
    'next': 'التالي',
    'noAccount': 'ليس لديك حساب؟',
    'noData': 'لا توجد بيانات',
    'notifications': 'الإشعارات',
    'notifications.clear_all': 'مسح الكل',
    'notifications.mark_read': 'تعليم كمقروء',
    'notifications.title': 'الإشعارات',
    'open': 'فتح',
    'operations.download_permit': 'تحميل التصريح',
    'operations.downloading_permit': 'جاري تحميل التصريح...',
    'operations.new_furnishing_request': 'طلب تأثيث جديد',
    'operations.title': 'مركز العمليات',
    'operationsCenter': 'مركز العمليات',
    'operationsSubtitle': 'من التصاريح إلى الصيانة، كل ما تحتاجه لإدارة جناحك في مكان واحد',
    'operationsTitle': 'إدارة عملياتك بالكامل',
    'ops.approvals': 'الموافقات',
    'ops.attachFile': 'إرفاق ملف',
    'ops.attachments': 'المرفقات',
    'ops.badgeContractor': 'باج مقاول',
    'ops.badgeEmployee': 'باج موظف',
    'ops.badgeVisitor': 'باج زائر',
    'ops.badges': 'الباجات',
    'ops.cancel': 'إلغاء',
    'ops.communications': 'المراسلات',
    'ops.description': 'الوصف',
    'ops.filterAll': 'الكل',
    'ops.furnishing': 'التأثيث',
    'ops.high': 'عالية',
    'ops.idNumber': 'رقم الهوية',
    'ops.low': 'منخفضة',
    'ops.maintenance': 'الصيانة',
    'ops.medium': 'متوسطة',
    'ops.newBadge': 'طلب باج جديد',
    'ops.newMaintenance': 'طلب صيانة',
    'ops.newPermit': 'طلب تصريح جديد',
    'ops.newSupply': 'طلب توريد',
    'ops.noRequests': 'لا توجد طلبات حالياً',
    'ops.permitEntry': 'تصريح دخول',
    'ops.permitExit': 'تصريح خروج',
    'ops.permitMaintenance': 'تصريح صيانة',
    'ops.permitSupply': 'تصريح توريد',
    'ops.permits': 'التصاريح',
    'ops.personName': 'اسم الشخص',
    'ops.priority': 'الأولوية',
    'ops.purpose': 'الغرض',
    'ops.requestDate': 'تاريخ الطلب',
    'ops.status.active': 'نشط',
    'ops.status.approved': 'معتمد',
    'ops.status.completed': 'مكتمل',
    'ops.status.expired': 'منتهي',
    'ops.status.inProgress': 'قيد التنفيذ',
    'ops.status.pending': 'قيد المراجعة',
    'ops.status.rejected': 'مرفوض',
    'ops.submit': 'إرسال الطلب',
    'ops.subtitle': 'إدارة جميع عمليات جناحك',
    'ops.supply': 'التوريد',
    'ops.title': 'مركز العمليات',
    'ops.validFrom': 'صالح من',
    'ops.validTo': 'صالح إلى',
    'ops.vehiclePlate': 'لوحة المركبة',
    'orContinueWith': 'أو المتابعة عبر',
    'otpSent': 'تم إرسال رمز التحقق',
    'payment.title': 'المدفوعات',
    'payment_status.paid': 'مدفوع',
    'payment_status.refunded': 'مسترد',
    'payments.amount_breakdown': 'تفاصيل المبلغ',
    'payments.amount_due': 'المبلغ المستحق',
    'payments.balance_due': 'الرصيد المستحق',
    'payments.bank': 'البنك',
    'payments.contract_signed_successfully_you': 'تم توقيع العقد بنجاح! يمكنك الآن المتابعة للدفع.',
    'payments.download_invoice': 'تحميل الفاتورة',
    'payments.invoice_breakdown': 'تفاصيل الفاتورة',
    'payments.no_invoices': 'لا توجد فواتير',
    'payments.paid': 'المدفوعة',
    'payments.pay_now': 'ادفع الآن',
    'payments.payment': 'الدفع',
    'payments.payment_gateway': 'بوابة الدفع',
    'payments.payment_method': 'طريقة الدفع',
    'payments.payment_received_successfully_receipt': 'تم استلام الدفعة بنجاح. الإيصال في المرفقات.',
    'payments.payment_successful': 'تم الدفع بنجاح!',
    'payments.payments_department': 'قسم المدفوعات',
    'payments.subtitle': 'إدارة الفواتير والمدفوعات',
    'payments.total_invoices': 'إجمالي الفواتير',
    'payments.what_payment_methods_are': 'ما هي طرق الدفع المتاحة؟',
    'pendingContracts': 'عقود معلقة',
    'pendingPayments': 'مدفوعات معلقة',
    'phone': 'الهاتف',
    'phoneNumber': 'رقم الجوال',
    'platformFeatures': 'مميزات المنصة',
    'poweredByAI': 'مدعوم بالذكاء الاصطناعي',
    'previous': 'السابق',
    'print': 'طباعة',
    'privacyPolicy': 'سياسة الخصوصية',
    'profile.activity_type': 'نوع النشاط',
    'profile.address': 'العنوان',
    'profile.company': 'اسم الشركة / المؤسسة',
    'profile.contact_us_via_platform': 'يمكنك التواصل عبر الرسائل في المنصة، أو الاتصال على 0535555900، أو إرسال بريد إلكتروني إلى info@mahamexpo.sa',
    'profile.edit': 'تعديل الملف',
    'profile.eg_maham_company': 'مثال: شركة مهام',
    'profile.email': 'البريد الإلكتروني',
    'profile.full_name': 'الاسم الكامل',
    'profile.nameen': 'name',
    'profile.phone': 'رقم الجوال',
    'profile.please_enter_a_valid': 'يرجى إدخال رقم جوال صحيح',
    'profile.please_fill_name_and': 'يرجى إكمال الاسم والبريد الإلكتروني',
    'profile.save': 'حفظ',
    'profile.title': 'الملف الشخصي',
    'quickActions': 'إجراءات سريعة',
    'realestate': 'عقارات',
    'recentBookings': 'أحدث الحجوزات',
    'region': 'المنطقة',
    'registerHere': 'سجّل هنا',
    'registerNow': 'سجّل الآن مجاناً',
    'requestService': 'طلب خدمة',
    'resendIn': 'إعادة الإرسال بعد',
    'resendOTP': 'إعادة إرسال الرمز',
    'reviews.amazing_experience_excellent_organization': 'تجربة رائعة! التنظيم ممتاز والخدمات متكاملة. الموقع استراتيجي وحركة الزوار كانت ممتازة. أنصح بشدة بالمشاركة في النسخة القادمة.',
    'reviews.by_rating': 'حسب التقييم',
    'reviews.my_reviews': 'تقييماتي',
    'reviews.organization': 'التنظيم',
    'reviews.please_select_a_rating': 'يرجى اختيار التقييم',
    'reviews.rating': 'التقييم',
    'reviews.request_submitted_it_will': 'تم إرسال الطلب بنجاح! سيتم مراجعته من قبل المشرف',
    'reviews.request_will_be_reviewed': 'سيتم مراجعة الطلب من قبل المشرف',
    'reviews.review_submitted_successfully': 'تم إرسال التقييم بنجاح',
    'reviews.reviews': 'تقييم',
    'reviews.services_quality': 'الخدمات',
    'reviews.share_your_expo_experience': 'شاركنا تجربتك في المعرض...',
    'reviews.submit_review': 'إرسال التقييم',
    'reviews.title': 'التقييمات',
    'reviews.write': 'كتابة تقييم',
    'riyadh': 'الرياض',
    'sar': 'ر.س',
    'satisfaction': 'رضا العملاء',
    'save': 'حفظ',
    'search': 'بحث',
    'seconds': 'ثانية',
    'securePayments': 'مدفوعات آمنة',
    'securePaymentsDesc': 'ادفع بأمان عبر بوابات دفع معتمدة مع فواتير إلكترونية متوافقة',
    'securePaymentsFeature': 'مدفوعات آمنة',
    'sendOTP': 'إرسال رمز التحقق',
    'services.add_to_cart': 'إضافة للسلة',
    'services.added_to_cart': 'تمت الإضافة للسلة',
    'services.cart': 'السلة',
    'services.cart_is_empty': 'السلة فارغة',
    'services.exhibitor_services': 'خدمات العارضين',
    'services.in_cart': 'في السلة',
    'services.no_matching_services': 'لا توجد خدمات مطابقة',
    'services.quote_request_sent_successfully': 'تم إرسال طلب عرض السعر بنجاح',
    'services.request_quote': 'طلب عرض سعر',
    'services.search': 'بحث في الخدمات',
    'services.service_fee': 'رسوم الخدمة',
    'services.service_fee_5': 'رسوم الخدمة (5%)',
    'services.title': 'الخدمات',
    'services.total': 'الإجمالي',
    'services.very_good_expo_great': 'معرض جيد جداً، الموقع مناسب والزوار كثر. الخدمات كانت جيدة والأسعار معقولة. يحتاج تحسين في التنظيم الداخلي.',
    'services.what_exhibitor_services_are': 'ما هي خدمات العارضين المتاحة؟',
    'sidebar.account': 'الحساب',
    'sidebar.analytics': 'التحليلات والذكاء',
    'sidebar.bookings': 'الحجوزات والعقود',
    'sidebar.control': 'لوحة التحكم',
    'sidebar.more': 'المزيد',
    'sidebar.operations': 'العمليات والخدمات',
    'sidebar.support': 'الدعم',
    'sidebar.team': 'الفريق',
    'sort': 'ترتيب',
    'startNow': 'ابدأ الآن',
    'status': 'الحالة',
    'status.active': 'نشط',
    'status.approved': 'معتمد',
    'status.available': 'متاح',
    'status.confirmed': 'مؤكد',
    'status.ended': 'منتهي',
    'status.pending': 'قيد المراجعة',
    'status.rejected': 'مرفوض',
    'status.reserved': 'محجوز',
    'status.sold': 'مباع',
    'step1Desc': 'أنشئ حسابك كتاجر وأكمل التحقق من هويتك بخطوات بسيطة',
    'step1Title': 'سجّل حسابك',
    'step2Desc': 'تصفح المعارض المتاحة واختر المعرض المناسب لنشاطك التجاري',
    'step2Title': 'اختر معرضك',
    'step3Desc': 'استخدم الخريطة التفاعلية لاختيار الجناح المثالي وأكمل الحجز',
    'step3Title': 'احجز جناحك',
    'step4Desc': 'وقّع العقد الرقمي وأتمم الدفع عبر بوابات آمنة',
    'step4Title': 'وقّع العقد وادفع',
    'step5Desc': 'اطلب خدمات التأثيث والتجهيز واحصل على تصاريح الدخول والباجات',
    'step5Title': 'جهّز جناحك',
    'step6Desc': 'شارك في المعرض وتابع أداءك عبر التحليلات المتقدمة',
    'step6Title': 'شارك وانجح',
    'submit': 'إرسال',
    'success': 'نجاح',
    'supplyDelivery': 'التوريد والتسليم',
    'supportDesc': 'فريق دعم متخصص متاح على مدار الساعة لمساعدتك',
    'supportFeature': 'دعم متواصل',
    'team.accountant': 'محاسبة',
    'team.active_member': 'عضو نشط',
    'team.add_invite': 'إضافة ودعوة',
    'team.add_member': 'إضافة عضو جديد',
    'team.chat_with_support_team': 'تحدث مع فريق الدعم',
    'team.email': 'البريد',
    'team.expo_manager': 'مدير المعارض',
    'team.member_added_and_invitation': 'تمت إضافة العضو وإرسال الدعوة',
    'team.member_name': 'اسم العضو',
    'team.member_removed': 'تم حذف العضو',
    'team.no_team_members_yet': 'لم تتم إضافة أعضاء بعد',
    'team.one_of_the_best': 'من أفضل المعارض التي شاركت فيها. الفريق المنظم محترف جداً والخدمات اللوجستية ممتازة. حققنا نتائج تجارية ممتازة.',
    'team.role': 'الدور',
    'team.service_coordinator': 'منسق خدمات',
    'team.support_team': 'فريق الدعم',
    'team.title': 'إدارة الفريق',
    'technology': 'تقنية وابتكار',
    'termsOfService': 'الشروط والأحكام',
    'thisMonth': 'هذا الشهر',
    'total': 'الإجمالي',
    'totalSpent': 'إجمالي المدفوعات',
    'traderLogin': 'دخول التاجر',
    'upcomingExpos': 'معارض قادمة',
    'upload': 'رفع',
    'verifiedTraders': 'تجار موثقون',
    'verify': 'تحقق',
    'viewAll': 'عرض الكل',
    'viewContracts': 'عرض العقود',
    'waitlist.join': 'انضم للقائمة',
    'waitlist.joined_waitlist': 'تم الانضمام لقائمة الانتظار',
    'waitlist.position': 'موقعك في القائمة',
    'waitlist.title': 'قائمة الانتظار',
    'warning': 'تحذير',
    'welcomeBack': 'مرحباً بك',
    'welcomeTrader': 'مرحباً',
    'whyMahamExpo': 'لماذا مهام إكسبو؟',
    'booking_flow.account_verification_documents': 'توثيق الحساب ورفع المستندات',
    'booking_flow.all_documents_must_be': 'يجب رفع جميع المستندات بصيغة PDF أو صورة واضحة. سيتم مراجعتها من قبل المشرف.',
    'booking_flow.all_transactions_are_encrypted': 'جميع المعاملات مشفرة ومحمية بتقنية SSL 256-bit',
    'booking_flow.amount_has_been_charged': 'تم خصم المبلغ بنجاح. يمكنك المتابعة لاستلام التأكيد.',
    'booking_flow.amount_paid': 'المبلغ المدفوع',
    'booking_flow.awaiting_review': 'في انتظار المراجعة',
    'booking_flow.back_to_dashboard': 'العودة للوحة التحكم',
    'booking_flow.book_exhibition_space': 'حجز مساحة عرض',
    'booking_flow.booking_confirmed_successfully': 'تم تأكيد حجزك بنجاح!',
    'booking_flow.booking_details': 'تفاصيل الحجز',
    'booking_flow.booking_no': 'رقم الحجز',
    'booking_flow.booking_terms_conditions': 'شروط وأحكام الحجز',
    'booking_flow.by_agreeing_i_confirm': 'بالموافقة، أقر بأنني قرأت وفهمت جميع الشروط والأحكام المذكورة أعلاه',
    'booking_flow.by_signing_you_agree': 'بتوقيعك، أنت توافق على جميع بنود العقد المذكورة أعلاه وتلتزم بتنفيذها.',
    'booking_flow.choose_the_booth_that': 'اختر الجناح المناسب لنشاطك التجاري من الخيارات المتاحة',
    'booking_flow.choose_your_preferred_payment': 'اختر طريقة الدفع المناسبة لإتمام حجزك',
    'booking_flow.clear': 'مسح التوقيع',
    'booking_flow.click_to_upload_file': 'اضغط لرفع الملف',
    'booking_flow.complete_payment': 'إتمام عملية الدفع',
    'booking_flow.congratulations_contract_and_invoice': 'تهانينا! تم إصدار العقد والفاتورة. سيتم إرسال نسخة إلى بريدك الإلكتروني ورقم جوالك.',
    'booking_flow.contract_date': 'تاريخ العقد',
    'booking_flow.contract_draft_electronic_signature': 'مسودة العقد والتوقيع الإلكتروني',
    'booking_flow.contract_no': 'رقم العقد',
    'booking_flow.contract_no_2': 'رقم العقد',
    'booking_flow.documents_uploaded': 'المستندات المرفوعة',
    'booking_flow.download_contract_pdf': 'تحميل العقد PDF',
    'booking_flow.draw_your_signature_here': 'وقّع هنا بالسحب',
    'booking_flow.electronic_signature': 'التوقيع الإلكتروني',
    'booking_flow.exhibition_space_booking_contract': 'عقد حجز مساحة عرض',
    'booking_flow.follow_the_steps_to': 'اتبع الخطوات لإتمام حجزك بسهولة',
    'booking_flow.i_agree_to_the': 'أوافق على الشروط والأحكام',
    'booking_flow.i_agree_to_the_2': 'أوافق على سياسة الخصوصية وسياسة الموقع',
    'booking_flow.i_consent_to_the': 'أوافق على معالجة بياناتي الشخصية وفقاً لسياسة الخصوصية المعتمدة',
    'booking_flow.important_all_documents_are': 'مهم: جميع المستندات مطلوبة',
    'booking_flow.including_vat': 'شامل ضريبة القيمة المضافة',
    'booking_flow.last_updated_march_2026': 'آخر تحديث: مارس 2026',
    'booking_flow.max_10_mb': 'حد أقصى 10 MB',
    'booking_flow.order_summary': 'ملخص الطلب',
    'booking_flow.payment_successful': 'تمت عملية الدفع بنجاح!',
    'booking_flow.please_read_the_terms': 'يرجى قراءة الشروط والأحكام بعناية والموافقة عليها للمتابعة',
    'booking_flow.please_upload_the_required': 'يرجى رفع المستندات المطلوبة للتحقق من حسابك قبل إتمام الحجز',
    'booking_flow.processing_payment': 'جاري معالجة الدفع...',
    'booking_flow.review_the_contract_details': 'راجع تفاصيل العقد ووقّع إلكترونياً للمتابعة',
    'booking_flow.reviewing_your_request': 'جاري مراجعة طلبك',
    'booking_flow.select_payment_method': 'اختر طريقة الدفع',
    'booking_flow.select_your_unit_or': 'اختر الوحدة أو المساحة',
    'booking_flow.sending_contract_invoice_copy': 'إرسال نسخة العقد والفاتورة',
    'booking_flow.terms_conditions_site_policy': 'الشروط والأحكام وسياسة الموقع',
    'booking_flow.the_supervisor_is_currently': 'يقوم المشرف حالياً بمراجعة مستنداتك والتحقق من صحتها. يرجى الانتظار...',
    'booking_flow.total_amount': 'المبلغ الإجمالي',
    'booking_flow.under_review': 'قيد المراجعة...',
    'booking_flow.uploaded': 'تم الرفع',
    'booking_flow.verified_approved': 'تم التحقق والموافقة',
    'booking_flow.your_documents_have_been': 'تم التحقق من مستنداتك بنجاح. يمكنك الآن المتابعة لتوقيع العقد.',
    'booking_flow.your_request_is_approved': 'تمت الموافقة على طلبك!',
    'booking_flow.your_request_will_be': 'سيتم مراجعة طلبك قريباً...',
    'contracts.vat_15': 'ضريبة القيمة المضافة 15%',
    'dashboard.active_events': 'الفعاليات النشطة',
    'messages.booth_design_service_request': 'تم تأكيد طلب خدمة تصميم البوث',
    'messages.your_booking_for_booth': 'تم تأكيد حجزك للجناح A12',
  },

  // ═══════════════════════════════════════════════════════════════
  // ENGLISH (Global SaaS English)
  // ═══════════════════════════════════════════════════════════════
  en: {
    'actions': 'Actions',
    'activeBookings': 'Active Bookings',
    'activeTraders': 'Active Traders',
    'activityType': 'Activity Type',
    'add': 'Add',
    'address': 'Address',
    'ai.online_ready': 'Online and ready to help',
    'ai.placeholder': 'Type your question here...',
    'ai.title': 'AI Assistant',
    'aiAssistantDesc': 'An AI assistant to help you choose the perfect booth and manage operations',
    'aiAssistantFeature': 'AI Assistant',
    'aiRecommendations': 'AI Recommendations',
    'allRightsReserved': 'All Rights Reserved',
    'amount': 'Amount',
    'analytics.conversion_rate': 'Conversion',
    'analytics.last_6_months': 'Last 6 months',
    'analytics.revenue': 'Revenue',
    'analytics.revenue_visitors': 'Revenue & Visitors',
    'analytics.title': 'Analytics',
    'analytics.top_expos': 'Top Performing Expos',
    'analytics.visitors': 'Visitors',
    'analyticsDesc': 'Comprehensive reports and analytics for your exhibition performance',
    'analyticsFeature': 'Advanced Analytics',
    'annualExpos': 'Annual Expos',
    'approvals': 'Approvals & Requests',
    'attachments': 'Attachments & Documents',
    'auth.account_created': 'Account created:',
    'auth.account_created_welcome_to': 'Account created! Welcome to Maham Expo',
    'auth.bank_letter_confirming_account': 'Bank letter confirming account details',
    'auth.successfully_registered': 'Successfully Registered!',
    'auth.valid_commercial_register_copy': 'Valid commercial register copy',
    'automotive': 'Automotive',
    'back': 'Back',
    'bookNewBooth': 'Book New Booth',
    'booking.area': 'Area',
    'booking.booth': 'Booth',
    'booking.price': 'Price',
    'booking.title': 'Bookings',
    'booking.zone': 'Zone',
    'booking_flow.complete_before_timeout': 'Complete booking before time expires',
    'booking_flow.select_activity': 'Select activity type',
    'bookings.3_competitors_booked_in': '3 competitors booked in the same expo',
    'bookings.book_30_days_early': 'Book 30 days early and get 15% discount',
    'bookings.booking_request_submitted': 'Booking request submitted!',
    'bookings.bookings': 'bookings',
    'bookings.completed_bookings': 'Completed Bookings',
    'bookings.excellent_i_would_like': 'Excellent, I would like to book it please',
    'bookings.expo': 'Expo',
    'bookings.my_bookings': 'My Bookings',
    'bookings.new_booking': 'New Booking',
    'bookings.no_bookings_found': 'No bookings found',
    'bookings.search_placeholder': 'Search by order ID or expo...',
    'booth_type.corner': 'Corner',
    'booth_type.island': 'Island',
    'booth_type.premium': 'Premium',
    'booth_type.standard': 'Standard',
    'booths': 'Available Booths',
    'boothsBooked': 'Booths booked this month',
    'brand.name': 'Maham Expo',
    'brand.tagline': 'Smart Expo Platform',
    'browseExpos': 'Browse Expos',
    'cancel': 'Cancel',
    'city': 'City',
    'close': 'Close',
    'comingSoon': 'Coming Soon',
    'common.': 'عربي',
    'common.active_events': 'active events',
    'common.advanced_filters': 'Advanced Filters',
    'common.all': 'All',
    'common.amenities': 'Amenities',
    'common.approved': 'Approved',
    'common.ar': 'ar',
    'common.available': 'Available:',
    'common.available_corner': 'Available (Corner)',
    'common.available_island': 'Available (Island)',
    'common.available_premium': 'Available (Premium)',
    'common.available_standard': 'Available (Standard)',
    'common.bank': 'Bank',
    'common.bank_certificate': 'Bank Certificate',
    'common.beneficiary': 'Beneficiary',
    'common.by_availability': 'By Availability',
    'common.by_date': 'By Date',
    'common.call_us': 'Call Us',
    'common.cancel': 'Cancel',
    'common.card': 'Card',
    'common.card_number': 'Card Number',
    'common.category': 'Category',
    'common.cats': 'cats',
    'common.city': 'City',
    'common.coming_soon': 'Coming Soon',
    'common.competitor_analysis': 'Competitor Analysis',
    'common.confirm': 'Confirm',
    'common.contact_us': 'Contact Us',
    'common.criteria': 'Criteria',
    'common.date': 'Date',
    'common.days': 'days',
    'common.download_receipt': 'Download Receipt',
    'common.due': 'Due',
    'common.entrance': 'Entrance',
    'common.enus': 'en-US',
    'common.expected_visitors': 'Expected Visitors',
    'common.expiry': 'Expiry',
    'common.filters': 'Filters',
    'common.helpful': 'Helpful',
    'common.hold_30min': 'Hold 30min',
    'common.important_notes': 'Important Notes:',
    'common.included_amenities': 'Included Amenities',
    'common.loading': 'Downloading...',
    'common.location': 'Location',
    'common.no_data': 'No data',
    'common.official': 'Official',
    'common.online': '• Online',
    'common.optional': 'Optional',
    'common.order': 'Order',
    'common.pending': 'Pending',
    'common.permissions': 'Permissions',
    'common.popular': 'Popular',
    'common.pricem': 'Price/m²',
    'common.print': 'Print',
    'common.printing': 'Printing...',
    'common.processing': 'Processing...',
    'common.quick_links': 'Quick Links',
    'common.read_only': 'Read only',
    'common.recent_activity': 'Recent Activity',
    'common.required': 'Required',
    'common.sar': 'SAR',
    'common.selected': 'Selected',
    'common.smart_recommendations': 'Smart Recommendations',
    'common.starts_from': 'Starting from',
    'common.status': 'Status',
    'common.status_tracking': 'Status Tracking',
    'common.submitted': 'Submitted',
    'common.subtotal': 'Subtotal',
    'common.suggested_expos': 'Suggested Expos',
    'common.total': 'Total',
    'common.track_request': 'Track Request',
    'common.trader': 'Trader',
    'common.type': 'Type',
    'common.unit': 'units',
    'common.uploading': 'Uploading...',
    'common.value': 'Value',
    'common.vat_15': 'VAT (15%)',
    'common.vat_certificate': 'VAT Certificate',
    'common.verified_successfully': 'Verified successfully',
    'common.view': 'View',
    'common.view_all': 'View All',
    'common.view_details': 'View Details',
    'common.yesterday': 'Yesterday',
    'common.your_comment': 'Your Comment',
    'communications': 'Communications',
    'companyName': 'Company Name',
    'completeProfile': 'Complete Your Profile',
    'confirm': 'Confirm',
    'contactUs': 'Contact Us',
    'contract.download': 'Download Contract',
    'contract.sign': 'Sign Contract',
    'contract.title': 'Contracts',
    'contract.view': 'View Contract',
    'contract_status.draft': 'Draft',
    'contract_status.signed': 'Signed',
    'contracts.add_team_members_to': 'Add team members to enable them to manage bookings and contracts',
    'contracts.after_booking_approval_the': 'After booking approval, the contract appears in Contracts page. Review terms and sign with one click.',
    'contracts.by_clicking_confirm_signature': 'By clicking "Confirm Signature" you agree to all contract terms',
    'contracts.confirm_signature': 'Confirm Signature',
    'contracts.contract_terms': 'Contract Terms',
    'contracts.contracts_will_appear_here': 'Contracts will appear here after your booking is approved',
    'contracts.digital_signature': 'Digital Signature',
    'contracts.draft_awaiting_signature': 'Draft - Awaiting Signature',
    'contracts.how_to_sign_contracts': 'How to sign contracts digitally?',
    'contracts.i_confirm_that_i': 'I confirm that I have read, understood, and agree to all contract terms',
    'contracts.my_contracts': 'My Contracts',
    'contracts.no_contracts_yet': 'No contracts yet',
    'contracts.of_course_we_will': 'Of course! We will send you a quote within 24 hours. Do you have a specific design concept?',
    'contracts.sign': 'Sign Contract',
    'contracts.signed': 'Signed',
    'contracts.signed_contracts': 'Signed Contracts',
    'contracts.supervisor_note': 'Reviewer Note',
    'contracts.unsigned': 'unsigned',
    'contracts.yes_i_want_a': 'Yes, I want a modern design with company colors (blue and gold)',
    'country': 'Country',
    'createAccount': 'Create Account',
    'ctaSubtitle': 'Join hundreds of successful traders and book your booth at the best exhibitions',
    'ctaTitle': 'Start Your Journey with Maham Expo',
    'dammam': 'Dammam',
    'dashboard.manage_expos': 'Expo Management',
    'dashboard.matching_expos': 'Expos matching your business type',
    'dashboard.monthly_bookings': 'Monthly Bookings',
    'dashboard.my_stats': 'My Stats',
    'dashboard.overall_rating': 'Overall Rating',
    'dashboard.recent_bookings': 'Recent Bookings',
    'dashboard.required_actions': 'Action Required',
    'dashboard.total_bookings': 'Total Bookings',
    'dashboard.total_payments': 'Total Spent',
    'dashboard.total_spent': 'Total Spent',
    'dashboard.upcoming_expos': 'Upcoming Expos',
    'dashboardSubtitle': 'Here\'s your activity summary',
    'date': 'Date',
    'delete': 'Delete',
    'details': 'Details',
    'digitalContracts': 'Digital Contracts',
    'digitalContractsDesc': 'Sign contracts electronically with full security and complete tracking',
    'download': 'Download',
    'edit': 'Edit',
    'email': 'Email',
    'employeeBadges': 'Employee Badges',
    'enterOTP': 'Enter the verification code sent to',
    'enterPhone': 'Enter phone number',
    'entryPermits': 'Entry & Exit Permits',
    'error': 'Error',
    'expo.about': 'About the Event',
    'expo.all_zones': 'All Zones',
    'expo.ask_about_the_best': 'Ask about the best units and personalized recommendations for Ala Khutah and Boulevard World',
    'expo.available_booths': 'Available Booths',
    'expo.available_units': 'Available Units',
    'expo.back_to_expos': 'Back to Expos',
    'expo.book_unit': 'Book Your Unit Now',
    'expo.booking_info': 'Booking Info',
    'expo.booth_a12': 'Booth A12',
    'expo.booth_design_service_request': 'Booth design service request confirmed. The designer will contact you soon.',
    'expo.booth_held_for_30': 'Booth held for 30 minutes',
    'expo.booth_price': 'Booth Price',
    'expo.booth_type_distribution': 'Booth Type Distribution',
    'expo.browse_available_expos_select': 'Browse available expos, select one, open the interactive map, and choose your booth. After submitting, it will be reviewed by the supervisor.',
    'expo.browse_services': 'Browse Services',
    'expo.categories': 'Categories',
    'expo.contact_booking': 'Contact for Booking',
    'expo.end_date': 'End Date',
    'expo.event_ended': 'This event has ended',
    'expo.hello_i_want_to': 'Hello, I want to request professional booth design service',
    'expo.hello_i_would_like': 'Hello, I would like to inquire about booth A12 booking',
    'expo.hello_yes_booth_a12': 'Hello! Yes, booth A12 is currently available. Area: 12m², Price: 13,500 SAR',
    'expo.hide_units': 'Hide Units',
    'expo.high_traffic_units': 'High Traffic Units',
    'expo.highlights': 'Highlights',
    'expo.how_to_book_a': 'How to book a booth?',
    'expo.join_the_waitlist_and': 'Join the waitlist and we will notify you when a premium booth becomes available',
    'expo.join_waitlist': 'Join Waitlist',
    'expo.marketing_reach': 'Marketing Reach',
    'expo.no_units': 'No units available',
    'expo.organizer': 'Organizer',
    'expo.other_events': 'Other Events',
    'expo.please_complete_identity_verification': 'Please complete identity verification to book booths.',
    'expo.premium_booth_waitlist': 'Premium Booth Waitlist',
    'expo.price_range': 'Price Range',
    'expo.start_browsing_expos_and': 'Start browsing expos and book your booth',
    'expo.start_date': 'Start Date',
    'expo.target_industries': 'Target Industries',
    'expo.units_near_entrance_get': 'Units near entrance get 40% more visits',
    'expo.verification_is_required_for': '• Verification is required for booking booths and signing contracts',
    'expo.view_units': 'View Units',
    'expo.visitor_demographics': 'Visitor Demographics',
    'expo.we_offer_36_services': 'We offer 36+ services including booth design, electricity, logistics, marketing, hospitality, photography, and more.',
    'expo.your_booking_for_booth': 'Your booking for booth A12 is confirmed. Please check the bookings page to complete the process.',
    'expo.your_identity_has_been': 'Your identity has been verified. You can now book booths and sign contracts.',
    'export': 'Export',
    'expos.active': 'Active',
    'expos.all': 'All',
    'expos.book_now': 'Book Now',
    'expos.booth': 'Booth',
    'expos.booths': 'Booths',
    'expos.completed': 'Completed',
    'expos.browse': 'Browse Expos',
    'expos.clear_filters': 'Clear Filters',
    'expos.no_results': 'No matching expos',
    'expos.search': 'Search Expos',
    'expos.search_placeholder': 'Search by name, city, or venue...',
    'expos.title': 'Expos',
    'expos.visitors': 'Visitors',
    'fashion': 'Fashion & Apparel',
    'featuresSubtitle': 'An integrated platform with everything a trader needs in one place',
    'filter': 'Filter',
    'food': 'Food & Beverage',
    'fullName': 'Full Name',
    'furnishing': 'Furnishing & Setup',
    'health': 'Health & Beauty',
    'help.faq': 'FAQ',
    'help.hello_how_can_we': 'Hello, how can we help?',
    'help.how_can_we_help': 'How can we help you today? We are here to serve you.',
    'help.how_to_contact_support': 'How to contact support?',
    'help.maham_expo_support': 'Maham Expo Support',
    'help.search_placeholder': 'Search FAQ...',
    'help.ticket': 'Support Ticket',
    'help.no_answer_create_ticket': 'Didn\'t find an answer? Create a support ticket and we\'ll respond within 24 hours',
    'help.title': 'Help Center',
    'heroSubtitle': 'Discover top exhibitions, book your ideal booth, and manage all operations from one AI-powered platform',
    'heroTitle': 'Your Smart Gateway to Exhibitions',
    'home.hero.cta': 'Start Now',
    'howItWorks': 'How It Works',
    'instantBooking': 'Instant Booking',
    'interactiveMap': 'Interactive Map',
    'interactiveMapDesc': 'Browse exhibition booths with an interactive 3D map with instant info about each booth',
    'jeddah': 'Jeddah',
    'journeySubtitle': 'Six simple steps to start your exhibition participation',
    'journeyTitle': 'Your Journey from Registration to Success',
    'kyc.all_documents_must_be': '• All documents must be valid and clearly readable',
    'kyc.commercial_register': 'Commercial Register',
    'kyc.complete_verification': 'Complete Verification',
    'kyc.document_removed': 'Document removed',
    'kyc.document_uploaded_successfully': 'Document uploaded successfully',
    'kyc.documents_are_reviewed_within': '• Documents are reviewed within 24-48 business hours',
    'kyc.documents_rejected_please_reupload': 'Documents rejected. Please re-upload clear and valid documents.',
    'kyc.documents_submitted_for_review': 'Documents submitted for review',
    'kyc.national_id': 'National ID',
    'kyc.please_upload_required_documents': 'Please upload required documents to complete verification',
    'kyc.status.pending': 'Pending',
    'kyc.status.rejected': 'Rejected',
    'kyc.status.submitted': 'Submitted',
    'kyc.status.verified': 'Verified',
    'kyc.title': 'Identity Verification (KYC)',
    'kyc.upload': 'Upload Document',
    'kyc.verification_progress': 'Verification Progress',
    'kyc.verification_status': 'Verification Status',
    'kyc.viewing_document': 'Viewing document',
    'kyc.your_documents_are_under': 'Your documents are under review. You will be notified within 24-48 hours.',
    'loading': 'Loading...',
    'login': 'Login',
    'login.complete_profile_subtitle': 'Complete your info to start your Maham Expo journey',
    'login.welcome': 'Welcome to Maham Expo! 👋',
    'loginSubtitle': 'Login to access your dashboard',
    'maintenance': 'Maintenance Requests',
    'makePayment': 'Make Payment',
    'makkah': 'Makkah',
    'map.add_compare': 'Add to Compare',
    'map.area': 'Area',
    'map.booth': 'Booth',
    'map.booth_unavailable': 'This booth is not available',
    'map.compare_booths': 'Compare Booths',
    'map.max_compare': 'Max 3 booths for comparison',
    'map.price': 'Price',
    'map.remove_compare': 'Remove from Compare',
    'map.select_type': 'Select type',
    'map.select_zone': 'Select region',
    'map.title': 'Interactive Map',
    'map.traffic': 'Traffic',
    'map.zone': 'Region',
    'messages.live_chat': 'Live Chat',
    'messages.new_message': 'New Message',
    'messages.search': 'Search Messages',
    'messages.select_conversation': 'Select a chat to start',
    'messages.start_conversation': 'Start Chat',
    'messages.thanks_for_your_message': 'Thanks for your message! We will reply as soon as possible.',
    'messages.title': 'Messages',
    'messages.type_message': 'Type a message...',
    'misc.accepted_formats_pdf_jpg': '• Accepted formats: PDF, JPG, PNG (max 5MB)',
    'misc.all_transactions_are_encrypted': 'All transactions are encrypted and PCI DSS compliant',
    'misc.back_to_home': 'Back to Home',
    'misc.bank_transfer_details': 'Bank Transfer Details',
    'misc.changes_saved_successfully': 'Changes saved successfully',
    'misc.click_to_select': 'Click to select',
    'misc.dammam_industrial_expo': 'Dammam Industrial Expo',
    'misc.drag_files_here_or': 'Drag files here or click to upload',
    'misc.early_bird_offer': 'Early Bird Offer',
    'misc.eg_nour_karam': 'e.g. Nour Karam',
    'misc.food_hospitality_expo': 'Food & Hospitality Expo',
    'misc.hold_time_expired': 'Hold time expired',
    'misc.jeddah_food_expo': 'Jeddah Food Expo',
    'misc.maham_ai_assistant': 'MAHAM AI Assistant',
    'misc.national_id_or_iqama': 'National ID or Iqama copy',
    'misc.new_approval_request': 'New Approval Request',
    'misc.page_not_found': 'Page Not Found',
    'misc.please_complete_required_fields': 'Please complete required fields',
    'misc.please_enter_a_title': 'Please enter a title',
    'misc.riyadh_tech_expo': 'Riyadh Tech Expo',
    'misc.thanks_for_your_feedback': 'Thanks for your feedback',
    'misc.try_changing_filters_or': 'Try changing filters or search',
    'misc.upload_new_attachment': 'Upload New Attachment',
    'misc.vat_registration_certificate': 'VAT registration certificate',
    'misc.we_accept_credit_cards': 'We accept credit cards, bank transfers, Apple Pay, and Mada.',
    'misc.you_will_be_notified': 'You will be notified when available',
    'month.apr': 'Apr',
    'month.feb': 'Feb',
    'month.jan': 'Jan',
    'month.jun': 'Jun',
    'month.mar': 'Mar',
    'month.may': 'May',
    'name': 'Name',
    'nav.ai': 'AI Assistant',
    'nav.analytics': 'Analytics',
    'nav.bookingFlow': 'New Booking',
    'nav.bookings': 'Bookings',
    'nav.contracts': 'Contracts',
    'nav.dashboard': 'Dashboard',
    'nav.expos': 'Expos',
    'nav.help': 'Help',
    'nav.kyc': 'Verification',
    'nav.logout': 'Logout',
    'nav.map': 'Map',
    'nav.messages': 'Messages',
    'nav.notifications': 'Notifications',
    'nav.operations': 'Operations',
    'nav.payments': 'Payments',
    'nav.profile': 'Profile',
    'nav.reviews': 'Reviews',
    'nav.services': 'Services',
    'nav.settings': 'Settings',
    'nav.team': 'Team',
    'nav.waitlist': 'Waitlist',
    'next': 'Next',
    'noAccount': 'Don\'t have an account?',
    'noData': 'No data',
    'notifications': 'Notifications',
    'notifications.clear_all': 'Clear All',
    'notifications.mark_read': 'Mark as Read',
    'notifications.title': 'Notifications',
    'open': 'Open',
    'operations.download_permit': 'Download Permit',
    'operations.downloading_permit': 'Downloading permit...',
    'operations.new_furnishing_request': 'New Furnishing Request',
    'operations.title': 'Operations Center',
    'operationsCenter': 'Operations Center',
    'operationsSubtitle': 'From permits to maintenance, everything you need to manage your booth in one place',
    'operationsTitle': 'Manage All Your Operations',
    'ops.approvals': 'Approvals',
    'ops.attachFile': 'Attach File',
    'ops.attachments': 'Attachments',
    'ops.badgeContractor': 'Contractor Badge',
    'ops.badgeEmployee': 'Employee Badge',
    'ops.badgeVisitor': 'Visitor Badge',
    'ops.badges': 'Badges',
    'ops.cancel': 'Cancel',
    'ops.communications': 'Communications',
    'ops.description': 'Description',
    'ops.filterAll': 'All',
    'ops.furnishing': 'Furnishing',
    'ops.high': 'High',
    'ops.idNumber': 'ID Number',
    'ops.low': 'Low',
    'ops.maintenance': 'Maintenance',
    'ops.medium': 'Medium',
    'ops.newBadge': 'New Badge Request',
    'ops.newMaintenance': 'New Maintenance Request',
    'ops.newPermit': 'New Permit Request',
    'ops.newSupply': 'New Supply Request',
    'ops.noRequests': 'No requests currently',
    'ops.permitEntry': 'Entry Permit',
    'ops.permitExit': 'Exit Permit',
    'ops.permitMaintenance': 'Maintenance Permit',
    'ops.permitSupply': 'Supply Permit',
    'ops.permits': 'Permits',
    'ops.personName': 'Person Name',
    'ops.priority': 'Priority',
    'ops.purpose': 'Purpose',
    'ops.requestDate': 'Request Date',
    'ops.status.active': 'Active',
    'ops.status.approved': 'Approved',
    'ops.status.completed': 'Completed',
    'ops.status.expired': 'Expired',
    'ops.status.inProgress': 'In Progress',
    'ops.status.pending': 'Pending',
    'ops.status.rejected': 'Rejected',
    'ops.submit': 'Submit Request',
    'ops.subtitle': 'Manage all your booth operations',
    'ops.supply': 'Supply',
    'ops.title': 'Operations Center',
    'ops.validFrom': 'Valid From',
    'ops.validTo': 'Valid To',
    'ops.vehiclePlate': 'Vehicle Plate',
    'orContinueWith': 'Or continue with',
    'otpSent': 'OTP Sent',
    'payment.title': 'Payments',
    'payment_status.paid': 'Paid',
    'payment_status.refunded': 'Refunded',
    'payments.amount_breakdown': 'Amount Breakdown',
    'payments.amount_due': 'Amount Due',
    'payments.balance_due': 'Balance Due',
    'payments.bank': 'Bank',
    'payments.contract_signed_successfully_you': 'Contract signed successfully! You can now proceed to payment.',
    'payments.download_invoice': 'Download Invoice',
    'payments.invoice_breakdown': 'Invoice Breakdown',
    'payments.no_invoices': 'No invoices',
    'payments.paid': 'Paid',
    'payments.pay_now': 'Pay Now',
    'payments.payment': 'Payment',
    'payments.payment_gateway': 'Payment Gateway',
    'payments.payment_method': 'Payment Method',
    'payments.payment_received_successfully_receipt': 'Payment received successfully. Receipt attached.',
    'payments.payment_successful': 'Payment successful!',
    'payments.payments_department': 'Payments Department',
    'payments.subtitle': 'Manage invoices and payments',
    'payments.total_invoices': 'Total Invoices',
    'payments.what_payment_methods_are': 'What payment methods are available?',
    'pendingContracts': 'Pending Contracts',
    'pendingPayments': 'Pending Payments',
    'phone': 'Phone',
    'phoneNumber': 'Phone Number',
    'platformFeatures': 'Platform Features',
    'poweredByAI': 'Powered by AI',
    'previous': 'Previous',
    'print': 'Print',
    'privacyPolicy': 'Privacy Policy',
    'profile.activity_type': 'Activity Type',
    'profile.address': 'Title',
    'profile.company': 'Company Name',
    'profile.contact_us_via_platform': 'Contact us via platform messages, call +966535555900, or email info@mahamexpo.sa',
    'profile.edit': 'Edit Profile',
    'profile.eg_maham_company': 'e.g. Maham Company',
    'profile.email': 'Email',
    'profile.full_name': 'Full Name',
    'profile.nameen': 'nameEn',
    'profile.phone': 'Phone Number',
    'profile.please_enter_a_valid': 'Please enter a valid phone number',
    'profile.please_fill_name_and': 'Please fill name and email',
    'profile.save': 'Save',
    'profile.title': 'Profile',
    'quickActions': 'Quick Actions',
    'realestate': 'Real Estate',
    'recentBookings': 'Recent Bookings',
    'region': 'Region',
    'registerHere': 'Register here',
    'registerNow': 'Register Now for Free',
    'requestService': 'Request Service',
    'resendIn': 'Resend in',
    'resendOTP': 'Resend Code',
    'reviews.amazing_experience_excellent_organization': 'Amazing experience! Excellent organization and complete services. Strategic location and visitor traffic was excellent. Highly recommend participating in the next edition.',
    'reviews.by_rating': 'By Rating',
    'reviews.my_reviews': 'My Reviews',
    'reviews.organization': 'Organization',
    'reviews.please_select_a_rating': 'Please select a rating',
    'reviews.rating': 'Rating',
    'reviews.request_submitted_it_will': 'Request submitted! It will be reviewed by the supervisor',
    'reviews.request_will_be_reviewed': 'Request will be reviewed by supervisor',
    'reviews.review_submitted_successfully': 'Review submitted successfully',
    'reviews.reviews': 'reviews',
    'reviews.services_quality': 'Services',
    'reviews.share_your_expo_experience': 'Share your expo experience...',
    'reviews.submit_review': 'Submit Review',
    'reviews.title': 'Reviews',
    'reviews.write': 'Write Review',
    'riyadh': 'Riyadh',
    'sar': 'SAR',
    'satisfaction': 'Client Satisfaction',
    'save': 'Save',
    'search': 'Search',
    'seconds': 'seconds',
    'securePayments': 'Secure Payments',
    'securePaymentsDesc': 'Pay securely through certified payment gateways with compliant e-invoices',
    'securePaymentsFeature': 'Secure Payments',
    'sendOTP': 'Send OTP',
    'services.add_to_cart': 'Add to Cart',
    'services.added_to_cart': 'Added to cart',
    'services.cart': 'Cart',
    'services.cart_is_empty': 'Cart is empty',
    'services.exhibitor_services': 'Exhibitor Services',
    'services.in_cart': 'In cart',
    'services.no_matching_services': 'No matching services',
    'services.quote_request_sent_successfully': 'Quote request sent successfully',
    'services.request_quote': 'Request Quote',
    'services.search': 'Search Services',
    'services.service_fee': 'Service Fee',
    'services.service_fee_5': 'Service Fee (5%)',
    'services.title': 'Services',
    'services.total': 'Total',
    'services.very_good_expo_great': 'Very good expo, great location and many visitors. Services were good and prices reasonable. Needs improvement in internal organization.',
    'services.what_exhibitor_services_are': 'What exhibitor services are available?',
    'sidebar.account': 'Account',
    'sidebar.analytics': 'Analytics & AI',
    'sidebar.bookings': 'Bookings & Contracts',
    'sidebar.control': 'Control Panel',
    'sidebar.more': 'More',
    'sidebar.operations': 'Operations & Services',
    'sidebar.support': 'Support',
    'sidebar.team': 'Team',
    'sort': 'Sort',
    'startNow': 'Start Now',
    'status': 'Status',
    'status.active': 'Active',
    'status.approved': 'Approved',
    'status.available': 'Available',
    'status.confirmed': 'Confirmed',
    'status.ended': 'Expired',
    'status.pending': 'Under Review',
    'status.rejected': 'Rejected',
    'status.reserved': 'Reserved',
    'status.sold': 'Sold',
    'step1Desc': 'Create your trader account and complete identity verification in simple steps',
    'step1Title': 'Register Your Account',
    'step2Desc': 'Browse available expos and choose the one that fits your business',
    'step2Title': 'Choose Your Expo',
    'step3Desc': 'Use the interactive map to select the perfect booth and complete booking',
    'step3Title': 'Book Your Booth',
    'step4Desc': 'Sign the digital contract and complete payment through secure gateways',
    'step4Title': 'Sign & Pay',
    'step5Desc': 'Order furnishing services and get entry permits and employee badges',
    'step5Title': 'Prepare Your Booth',
    'step6Desc': 'Participate in the expo and track your performance with advanced analytics',
    'step6Title': 'Participate & Succeed',
    'submit': 'Submit',
    'success': 'Success',
    'supplyDelivery': 'Supply & Delivery',
    'supportDesc': 'Dedicated support team available 24/7 to assist you',
    'supportFeature': 'Continuous Support',
    'team.accountant': 'Accounting',
    'team.active_member': 'Active Member',
    'team.add_invite': 'Add & Invite',
    'team.add_member': 'Add New Member',
    'team.chat_with_support_team': 'Chat with support team',
    'team.email': 'Email',
    'team.expo_manager': 'Expo Manager',
    'team.member_added_and_invitation': 'Member added and invitation sent',
    'team.member_name': 'Member Name',
    'team.member_removed': 'Member removed',
    'team.no_team_members_yet': 'No team members yet',
    'team.one_of_the_best': 'One of the best expos I have participated in. The organizing team is very professional and logistics services are excellent. We achieved excellent business results.',
    'team.role': 'Role',
    'team.service_coordinator': 'Services Coordinator',
    'team.support_team': 'Support Team',
    'team.title': 'Team Management',
    'technology': 'Technology & Innovation',
    'termsOfService': 'Terms of Service',
    'thisMonth': 'this month',
    'total': 'Total',
    'totalSpent': 'Total Payments',
    'traderLogin': 'Trader Login',
    'upcomingExpos': 'Upcoming Expos',
    'upload': 'Upload',
    'verifiedTraders': 'Verified Traders',
    'verify': 'Verify',
    'viewAll': 'View All',
    'viewContracts': 'View Contracts',
    'waitlist.join': 'Join Waitlist',
    'waitlist.joined_waitlist': 'Joined waitlist',
    'waitlist.position': 'Your Position',
    'waitlist.title': 'Waitlist',
    'warning': 'Warning',
    'welcomeBack': 'Welcome Back',
    'welcomeTrader': 'Welcome',
    'whyMahamExpo': 'Why Maham Expo?',
    'booking_flow.account_verification_documents': 'Account Verification & Documents',
    'booking_flow.all_documents_must_be': 'All documents must be uploaded as PDF or clear image. They will be reviewed by the supervisor.',
    'booking_flow.all_transactions_are_encrypted': 'All transactions are encrypted and protected with 256-bit SSL',
    'booking_flow.amount_has_been_charged': 'Amount has been charged successfully. You can proceed to receive confirmation.',
    'booking_flow.amount_paid': 'Amount Paid',
    'booking_flow.awaiting_review': 'Awaiting Review',
    'booking_flow.back_to_dashboard': 'Back to Dashboard',
    'booking_flow.book_exhibition_space': 'Book Exhibition Space',
    'booking_flow.booking_confirmed_successfully': 'Booking Confirmed Successfully!',
    'booking_flow.booking_details': 'Booking Details',
    'booking_flow.booking_no': 'Booking No.',
    'booking_flow.booking_terms_conditions': 'Booking Terms & Conditions',
    'booking_flow.by_agreeing_i_confirm': 'By agreeing, I confirm that I have read and understood all the terms and conditions above',
    'booking_flow.by_signing_you_agree': 'By signing, you agree to all contract terms mentioned above and commit to their execution.',
    'booking_flow.choose_the_booth_that': 'Choose the booth that suits your business from available options',
    'booking_flow.choose_your_preferred_payment': 'Choose your preferred payment method to complete your booking',
    'booking_flow.clear': 'Clear',
    'booking_flow.click_to_upload_file': 'Click to upload file',
    'booking_flow.complete_payment': 'Complete Payment',
    'booking_flow.congratulations_contract_and_invoice': 'Congratulations! Contract and invoice have been issued. A copy will be sent to your email and phone.',
    'booking_flow.contract_date': 'Contract Date',
    'booking_flow.contract_draft_electronic_signature': 'Contract Draft & Electronic Signature',
    'booking_flow.contract_no': 'Contract No.',
    'booking_flow.contract_no_2': 'Contract No.',
    'booking_flow.documents_uploaded': 'Documents uploaded',
    'booking_flow.download_contract_pdf': 'Download Contract PDF',
    'booking_flow.draw_your_signature_here': 'Draw your signature here',
    'booking_flow.electronic_signature': 'Electronic Signature',
    'booking_flow.exhibition_space_booking_contract': 'Exhibition Space Booking Contract',
    'booking_flow.follow_the_steps_to': 'Follow the steps to complete your booking easily',
    'booking_flow.i_agree_to_the': 'I agree to the Terms & Conditions',
    'booking_flow.i_agree_to_the_2': 'I agree to the Privacy Policy & Site Policy',
    'booking_flow.i_consent_to_the': 'I consent to the processing of my personal data in accordance with the approved privacy policy',
    'booking_flow.important_all_documents_are': 'Important: All documents are required',
    'booking_flow.including_vat': 'Including VAT',
    'booking_flow.last_updated_march_2026': 'Last updated: March 2026',
    'booking_flow.max_10_mb': 'Max 10 MB',
    'booking_flow.order_summary': 'Order Summary',
    'booking_flow.payment_successful': 'Payment Successful!',
    'booking_flow.please_read_the_terms': 'Please read the terms and conditions carefully and accept them to proceed',
    'booking_flow.please_upload_the_required': 'Please upload the required documents to verify your account before completing the booking',
    'booking_flow.processing_payment': 'Processing payment...',
    'booking_flow.review_the_contract_details': 'Review the contract details and sign electronically to proceed',
    'booking_flow.reviewing_your_request': 'Reviewing Your Request',
    'booking_flow.select_payment_method': 'Select Payment Method',
    'booking_flow.select_your_unit_or': 'Select Your Unit or Space',
    'booking_flow.sending_contract_invoice_copy': 'Sending Contract & Invoice Copy',
    'booking_flow.terms_conditions_site_policy': 'Terms, Conditions & Site Policy',
    'booking_flow.the_supervisor_is_currently': 'The supervisor is currently reviewing your documents and verifying them. Please wait...',
    'booking_flow.total_amount': 'Total Amount',
    'booking_flow.under_review': 'Under review...',
    'booking_flow.uploaded': 'Uploaded',
    'booking_flow.verified_approved': 'Verified & Approved',
    'booking_flow.your_documents_have_been': 'Your documents have been verified successfully. You can now proceed to sign the contract.',
    'booking_flow.your_request_is_approved': 'Your Request is Approved!',
    'booking_flow.your_request_will_be': 'Your request will be reviewed shortly...',
    'contracts.vat_15': 'VAT 15%',
    'dashboard.active_events': 'Active Events',
    'messages.booth_design_service_request': 'Booth design service request confirmed',
    'messages.your_booking_for_booth': 'Your booking for booth A12 is confirmed',
  },
};

interface LanguageContextType {
  language: LangCode;
  setLanguage: (lang: LangCode) => void;
  t: (key: string) => string;
  isRTL: boolean;
  dir: 'rtl' | 'ltr';
  languages: LangInfo[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LangCode>(() => {
    const saved = localStorage.getItem('maham-lang') as LangCode;
    return saved && translations[saved] ? saved : 'ar';
  });

  const setLanguage = useCallback((lang: LangCode) => {
    setLanguageState(lang);
    localStorage.setItem('maham-lang', lang);
    const langInfo = LANGUAGES.find(l => l.code === lang);
    if (langInfo) {
      document.documentElement.dir = langInfo.dir;
      document.documentElement.lang = lang;
    }
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  }, [language]);

  const langInfo = LANGUAGES.find(l => l.code === language);
  const isRTL = langInfo?.dir === 'rtl';

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t,
      isRTL,
      dir: isRTL ? 'rtl' : 'ltr',
      languages: LANGUAGES,
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
